networks:
  app:

services:
  db:
    image: postgres:16
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    env_file:
     - pg_db.env
    healthcheck:
       test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
       interval: 30s
       timeout: 10s
       retries: 3
       start_period: 60s
    restart: unless-stopped
    networks:
      app:

  api:
    build:
     context: .
     dockerfile: api/Dockerfile
    container_name: api
    ports:
     - "8080:8000"
    depends_on:
     - db
    env_file:
     - api/.env
    networks:
      app:
